services:
  service:
    build: ./service
    ports:
      - "8000:8000"
    depends_on:
      - db
      - jaeger
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: o11y
      DB_HOST: db
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: o11y
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://user:pass@db:5432/o11y?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/terraform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/terraform/alertmanager/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - service
      - postgres-exporter
      - alertmanager

  locust:
    build: ./locust
    ports:
      - "8089:8089"
    depends_on:
      - service
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./infra/terraform/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./infra/terraform/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./infra/terraform/alertmanager/alerts.yml:/etc/alertmanager/alerts.yml:ro
    ports:
      - "9093:9093"
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"    # OTLP/Thrift для спанов
      - "16686:16686"      # UI



volumes:
  db-data:
