{
 "title": "Cat food dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(app_request_latency_seconds_bucket{job=\"cat-food-service\"}[5m])\n  ) by (le)\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "RPS PostgreSQL 2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"o11y\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (5xx 4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{endpoint!=\"/metrics\",code=~\"4..|5..\"}[5m]))\n/\nsum(rate(app_requests_total{endpoint!=\"/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"o11y\"}[1m])",
     "legendFormat": "rps"
    }
   ]
  }
 ]
}